=== Solen-Kerdraon/Bon-de-commande-XML/Bdc.dtd
<?xml version="1.0" encoding="utf-8"?>
<!ELEMENT BDC (Entreprise, Entreprise, Date, Montanttotal, LDC+)>
<!ELEMENT Entreprise (Nom, Adresse, NTelephone, NTelecopie?)>
<!ELEMENT LDC (Reference, Intitule, Quantité, PrixUnitaire)>
<!ELEMENT Date (#PCDATA)>
<!ELEMENT Montanttotal (#PCDATA)>
<!ELEMENT Nom (#PCDATA)>
<!ELEMENT Adresse (#PCDATA)>
<!ELEMENT NTelephone (#PCDATA)>
<!ELEMENT NTelecopie (#PCDATA)>
<!ELEMENT Reference (#PCDATA)>
<!ELEMENT Intitule (#PCDATA)>
<!ELEMENT Quantité (#PCDATA)>
<!ELEMENT PrixUnitaire (#PCDATA)>

=== Solen-Kerdraon/Bon-de-commande-XML/Bdc.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE BDC SYSTEM "Bdc.dtd">
<BDC>
<Entreprise>
   <Nom>E1</Nom>
   <Adresse>A1</Adresse>
   <NTelephone>00.00.00.00.00</NTelephone>
   <NTelecopie>n°xx</NTelecopie>
</Entreprise>
<Entreprise>
   <Nom>E2</Nom>
   <Adresse>A2</Adresse>
   <NTelephone>00.00.00.00.00</NTelephone>
   <NTelecopie>n°xx</NTelecopie>
</Entreprise>
<Date>01/01/2024</Date>
<Montanttotal>xxx€</Montanttotal>
<LDC>
    <Reference>n°xxx</Reference>
    <Intitule>Intitulé</Intitule>
    <Quantité>00</Quantité>
    <PrixUnitaire>xx€</PrixUnitaire>
</LDC>
</BDC>
